name: Update Exchange Rate

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-rate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch Rate
        run: |
          RATE=$(curl -s https://www.cbr-xml-daily.ru/daily_json.js | jq '.Valute.EUR.Value')
          echo "{ \"rate\": $RATE, \"date\": \"$(date)\" }" > rate.json

      - name: Commit and Push
        run: |
          git config --global user.name 'RateBot'
          git config --global user.email 'bot@rxde.online'
          git add rate.json
          git commit -m "Update rate" || exit 0
          git push
